# Generated by Django 6.0.6 on 2026-06-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_alumno_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='examenes.asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursadas', to='examenes.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='examenes.alumno')),
                ('cursada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='examenes.cursada')),
            ],
            options={
                'unique_together': {('alumno', 'cursada')},
            },
        ),
        migrations.AddField(
            model_name='cursada',
            name='alumnos',
            field=models.ManyToManyField(related_name='cursadas', through='examenes.Inscripcion', to='examenes.alumno'),
        ),
    ]
