# Generated by Django 6.0.6 on 2026-06-14 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_alter_inscripcion_unique_together_examen_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'cursada')},
        ),
    ]
